### ISSUE TITLE
error processing davinci ctl

### ISSUE THREAD

**Issue by hegde20006** [baldavenger/DCTLs#1]
hi ,
getting "error processing davinci ctl"
system: resolve 14
mac os: 10.12.6
graphic cards: d700
some dctl from ur pack seems to work fine but others give "error processing davinci ctl"
thanks in advance
files copied in LUT folder

**Comment by baldavenger** [comment]
Which specific DCTL returned this error? It might be a compatibility issue, as DCTLs are primarily based on CUDA, and your d700 is OpenCL only. There should be a workable solution though.
